### ISSUE TITLE
aarch64-darwin build cycle

### ISSUE THREAD

**Issue by rignet-bicteg** [nmattia/niv#343] opened 2021-11-25 08:50 UTC
I'm runnning nix 2.4 on macOS Monterey, I run `nix-env -iA nixpkgs.niv` and I get the following error:

```
Installing library in /nix/store/ljqi6swgq4vckrigkqpjc1c6wrdf53gm-niv-0.2.19/lib/ghc-8.10.7/aarch64-osx-ghc-8.10.7/niv-0.2.19-AtMpwLNrtqAEZxlNAy7E8l
Installing executable niv in /nix/store/99vz7gxkd70dxaxz8jz55p8l83x93k0m-niv-0.2.19-bin/bin
Warning: The directory
/nix/store/99vz7gxkd70dxaxz8jz55p8l83x93k0m-niv-0.2.19-bin/bin is not in the
system search path.
/nix/store/wn9v5lcin8lsfzhpvfp6pypb78vzi7b0-cctools-binutils-darwin-949.0.1/bin/strip: changes being made to the file will invalidate the code signature in: /nix/store/99vz7gxkd70dxaxz8jz55p8l83x93k0m-niv-0.2.19-bin/bin/niv
Registering library for niv-0.2.19..
post-installation fixup
strip is /nix/store/hi81iavwbigd3gssp3mw0l90vap8p0ji-clang-wrapper-11.1.0/bin/strip
stripping (with command strip and flags -S) in /nix/store/ljqi6swgq4vckrigkqpjc1c6wrdf53gm-niv-0.2.19/lib
patching script interpreter paths in /nix/store/ljqi6swgq4vckrigkqpjc1c6wrdf53gm-niv-0.2.19
strip is /nix/store/hi81iavwbigd3gssp3mw0l90vap8p0ji-clang-wrapper-11.1.0/bin/strip
patching script interpreter paths in /nix/store/7hjab2q9673adkf2xmyym53pkrk4bn5y-niv-0.2.19-data
strip is /nix/store/hi81iavwbigd3gssp3mw0l90vap8p0ji-clang-wrapper-11.1.0/bin/strip
stripping (with command strip and flags -S) in /nix/store/99vz7gxkd70dxaxz8jz55p8l83x93k0m-niv-0.2.19-bin/bin
patching script interpreter paths in /nix/store/99vz7gxkd70dxaxz8jz55p8l83x93k0m-niv-0.2.19-bin
error: cycle detected in build of '/nix/store/shp29br5046r5ih9z5hfxv5aynhzkxbk-niv-0.2.19.drv' in the references of output 'bin' from output 'out'
```

Any idea if I can do a quick fix?

**Comment by adrian-gierakowski** [comment] 2021-11-25 09:26
See https://github.com/nmattia/niv/issues/332#issuecomment-958449218

**Comment by nmattia** [comment] 2021-11-25 09:35
Closing as duplicate of #332 (thanks @adrian-gierakowski !)

**Closed by nmattia** 2021-11-25 09:35 UTC
