### ISSUE TITLE
Add timestamp to sources.json repositories

### ISSUE THREAD

**Issue by Profpatsch** [nmattia/niv#175] opened 2020-01-08 11:35 UTC
`nix-prefetch-git` adds a timestamp to its output, which is very nice when you are skimming a sources file and want to know how old e.g. the nixpkgs version is.

`nix-prefetch-git`:
```
{
  "url": "https://github.com/nixos/nixpkgs-channels.git",
  "rev": "9beb0d1ac2ebd6063efbdc4d3631f8ce137bbf90",
  "date": "2020-01-06T05:49:56-05:00",
  "sha256": "1v95779di35qhrz70p2v27kmwm09h8pgh74i1wc72v0zp3bdrf50",
  "fetchSubmodules": false
}
```

niv:
```
    "nixpkgs": {
        "branch": "nixos-unstable",
        "description": "A read-only mirror of NixOS/nixpkgs tracking the released channels. Send issues and PRs to",
        "homepage": "https://github.com/NixOS/nixpkgs",
        "owner": "NixOS",
        "repo": "nixpkgs-channels",
        "rev": "e19054ab3cd5b7cc9a01d0efc71c8fe310541065",
        "sha256": "0b92yhkj3pq58svyrx7jp0njhaykwr29079izqn6qs638v8zvhl2",
        "type": "tarball",
        "url": "https://github.com/NixOS/nixpkgs-channels/archive/e19054ab3cd5b7cc9a01d0efc71c8fe310541065.tar.gz",
        "url_template": "https://github.com/<owner>/<repo>/archive/<rev>.tar.gz"
    }
```

The same `date` field would be nice.

**Comment by nmattia** [comment] 2020-01-08 11:39
@Profpatsch makes sense! This appears to be the same as https://github.com/nmattia/niv/issues/111, correct?

**Comment by Profpatsch** [comment] 2020-01-16 17:25
Timestamp of latest commit makes sense, yes.

**Comment by nmattia** [comment] 2020-01-31 16:03
Closing as duplicate of #111

**Closed by nmattia** 2020-01-31 16:03 UTC
